spring:
  application:
    name: index-codes-service
  zipkin:
    base-url: http://localhost:9411
  redis:
    password: 123zxc
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/